package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type templateFile struct {
	source string
	target string
	data   []byte
}

func main() {
	source := flag.String("source", "", "canonical deploy template directory")
	output := flag.String("output", "", "generated Go output")
	check := flag.Bool("check", false, "fail when generated output differs")
	flag.Parse()
	if *source == "" || *output == "" {
		fatal(errors.New("source and output are required"))
	}
	generated, err := generate(*source)
	if err != nil {
		fatal(err)
	}
	if *check {
		current, err := os.ReadFile(*output)
		if err != nil || !bytes.Equal(current, generated) {
			fatal(errors.New("templates_generated.go differs from deploy canonical templates; run go generate ./internal/repositorycontract"))
		}
		return
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fatal(err)
	}
}

func generate(root string) ([]byte, error) {
	specs := []templateFile{
		{source: "AGENTS.block.md"},
		{source: ".github/workflows/workflow-contract.yml", target: ".github/workflows/workflow-contract.yml"},
		{source: "docs/agents/domain.md", target: "docs/agents/domain.md"},
		{source: "docs/agents/domain.multi-context.md"},
		{source: "docs/agents/issue-tracker.md", target: "docs/agents/issue-tracker.md"},
	}
	for index := range specs {
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(specs[index].source)))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", specs[index].source, err)
		}
		specs[index].data = []byte(strings.ReplaceAll(string(data), "\r\n", "\n"))
	}
	sort.Slice(specs, func(i, j int) bool { return specs[i].source < specs[j].source })
	hash := sha256.New()
	for _, spec := range specs {
		hash.Write([]byte(spec.source))
		hash.Write([]byte{0})
		hash.Write(spec.data)
		hash.Write([]byte{0})
	}
	bySource := make(map[string]templateFile, len(specs))
	for _, spec := range specs {
		bySource[spec.source] = spec
	}
	var body bytes.Buffer
	body.WriteString("// Code generated by go generate; DO NOT EDIT.\n\npackage repositorycontract\n\n")
	fmt.Fprintf(&body, "const contractTemplateSourceSHA256 = %q\n\n", hex.EncodeToString(hash.Sum(nil)))
	fmt.Fprintf(&body, "var block = []byte(%s)\n\n", strconv.Quote(string(bySource["AGENTS.block.md"].data)))
	fmt.Fprintf(&body, "var multiContextDomain = []byte(%s)\n\n", strconv.Quote(string(bySource["docs/agents/domain.multi-context.md"].data)))
	body.WriteString("var wholeFiles = map[string][]byte{\n")
	for _, spec := range specs {
		if spec.target != "" {
			fmt.Fprintf(&body, "%s: []byte(%s),\n", strconv.Quote(spec.target), strconv.Quote(string(spec.data)))
		}
	}
	body.WriteString("}\n")
	formatted, err := format.Source(body.Bytes())
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
